language: haskell

ghc:
  - 7.8

before_install:
  - git clone --depth 1 https://github.com/haskell-servant/servant.git -b servant-0.2
  - git clone --depth 1 https://github.com/haskell-servant/servant-server.git -b servant-server-0.2
  - cabal sandbox init
  - cabal sandbox add-source servant/
  - cabal sandbox add-source servant-server/

notifications:
  irc:
    channels:
      - "irc.freenode.org#servant"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
