# Let's try to keep resolver at the first day of the month
resolver: nightly-2018-03-01
packages:
- servant-client/
- servant-client-core/
- servant-docs/
- servant-foreign/
- servant-server/
- servant/

extra-deps:
- cabal-doctest-1.0.6
- http-api-data-0.3.7.2
- http-types-0.12
- text-1.2.3.0
- aeson-1.3.0.0
- exceptions-0.10.0
- aeson-compat-0.3.7.1
- free-5.0.1
- lens-4.16
- random-bytestring-0.1.3
- pcg-random-0.1.3.5

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/
